scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  # Create a job for Docker daemons.
  - job_name: "docker"
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: nodes
    relabel_configs:
      # Fetch metrics on port 9323.
      - source_labels: [__meta_dockerswarm_node_address]
        target_label: __address__
        replacement: $1:9323
      # Set hostname as instance label
      - source_labels: [__meta_dockerswarm_node_hostname]
        target_label: instance
  # - job_name: 'cadvisor'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: [cadvisor:8080, 10.168.64.61:8088, 10.168.64.62:8088, 10.168.64.63:8088]
  #   # dns_sd_configs:
  #   # - names:
  #   #   - 'tasks.cadvisor'
  #   #   type: 'A'
  #   #   port: 8080
  # - job_name: 'node'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: [node-exporter:9100, 10.168.64.61:9100, 10.168.64.62:9100, 10.168.64.63:9100]
  #   # dns_sd_configs:
  #   # - names:
  #   #   - 'tasks.node-exporter'
  #   #   type: 'A'
  #   #   port: 9100
